---
title: "Black-White Mortality Crossover"
author: Casey Breen
---

Summary: Code to estimate Black-White mortality disparities 


```{r}
## library packages 
library(tidyverse)
library(data.table)
library(here)
library(cowplot)

## read in dmf 
dmf <- fread(here("data/censoc_dmf_v2.1_linked.csv"))

## recode race 
## restrict to conservative matches 
## restrict to people born in the US 
dmf <- dmf %>%
  janitor::clean_names() %>%
  mutate(race = case_when(
    race == 1 ~ "White Americans",
    race == 2 ~ "Black Americans"
  )) %>%
  filter(link_abe_exact_conservative == 1) %>%
  filter(bpl < 15000)


## recode education
dmf <- dmf %>%
  censocdev::recode_education(educ_var = educd) 
```


## full bw mortality crossover plots 


```{r}
## Estimate Black-White mortality crossover
estimated_mortality_rates <- dmf %>%
  filter(byear %in% c(1890:1905)) %>%
  filter(race == "White Americans" | race == "Black Americans") %>%
  group_by(death_age, race) %>%
  summarize(weighted_total = n()) %>%
  group_by(race) %>%
  mutate(lx = sum(weighted_total) - cumsum(weighted_total) + weighted_total) %>%
  mutate(mx = weighted_total / (lx + lead(lx) / 2)) %>%
  mutate(hazard = log(mx))

pooled_bwcrossover <- estimated_mortality_rates %>%
  filter(death_age %in% c(75:100)) %>%
  ggplot() +
  geom_line(aes(x = death_age, y = hazard, color = race)) +
  geom_point(aes(x = death_age, y = hazard, shape = race, color = race), size = 2.5, fill = "white") +
  theme_cowplot() + 
  geom_vline(xintercept = 86, linetype = "dashed") +
  theme(legend.position = "bottom") +
  labs(
    x = "Age",
    y = "Log(Mx)",
    title = "Mortality Crossovers (Men)",
    subtitle = "Pooled cohorts of 1890 - 1905"
  ) +
    scale_shape_manual(values = c(21, 24)) + 
  ggsci::scale_colour_lancet() +
  theme(legend.title = element_blank()) +
  theme(
    legend.position = c(.999, 0.001),
    legend.justification = c("right", "bottom"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6),
    legend.background = element_rect(color = "black", size = .5, linetype = "solid")
  )

estimated_mortality_rates_noheap <- dmf %>%
  filter(byear %in% c(1891:1894, 1896:1899, 1901:1904)) %>%
  filter(race == "White Americans" | race == "Black Americans") %>%
  group_by(death_age, race) %>%
  summarize(weighted_total = n()) %>%
  group_by(race) %>%
  mutate(lx = sum(weighted_total) - cumsum(weighted_total) + weighted_total) %>%
  mutate(mx = weighted_total / (lx + lead(lx) / 2)) %>%
  mutate(hazard = log(mx))

pooled_bwcrossover_noheap <- estimated_mortality_rates_noheap %>%
  filter(death_age %in% c(75:100)) %>%
  ggplot() +
  geom_line(aes(x = death_age, y = hazard, color = race)) +
  geom_point(aes(x = death_age, y = hazard, shape = race, color = race), size = 2.5, fill = "white") +
  cowplot::theme_cowplot() +
  geom_vline(xintercept = 86, linetype = "dashed") +
  theme(legend.position = "bottom") +
  scale_shape_manual(values = c(21, 24)) + 
  labs(
    x = "Age",
    y = "Log(Mx)",
    title = "",
    subtitle = "Pooled cohorts of 1891-1894, 1896-1899, 1901-1904"
  ) +
  ggsci::scale_colour_lancet() +
  theme(legend.title = element_blank()) +
  theme(
    legend.position = c(.999, 0.001),
    legend.justification = c("right", "bottom"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6),
    legend.background = element_rect(color = "black", size = .5, linetype = "solid")
  )

crossover_figure <- plot_grid(pooled_bwcrossover, pooled_bwcrossover_noheap, labels = "auto", ncol = 1)

ggsave(plot = crossover_figure, filename = here("figures/bw_crossover.png"), width = 7.5, height = 10)
```

## education 

```{r}
## Calculate mortality rates — high education 
mortality_rates_higheduc <- dmf %>%
  filter(educ_yrs >= 8) %>%
  filter(byear %in% c(1890:1905)) %>%
  filter(race == "White Americans" | race == "Black Americans") %>%
  group_by(death_age, race) %>%
  summarize(weighted_total = n()) %>%
  group_by(race) %>%
  mutate(lx = sum(weighted_total) - cumsum(weighted_total) + weighted_total) %>%
  mutate(mx = weighted_total / (lx + lead(lx) / 2)) %>%
  mutate(hazard = log(mx)) %>%
  mutate(hazard_avg = zoo::rollmean(x = hazard, k = 3, na.pad = T))

## Plot — low education  
pooled_bwcrossover_highed <- mortality_rates_higheduc %>%
  filter(death_age %in% c(75:100)) %>%
  ggplot() +
  geom_line(aes(x = death_age, y = hazard, color = race)) +
  geom_point(aes(x = death_age, y = hazard, shape = race, color = race), size = 2.5, fill = "white") +
  theme_cowplot() + 
  geom_vline(xintercept = 86, linetype = "dashed") +
  theme(legend.position = "bottom") +
  labs(
    x = "Age",
    y = "Log(Mx)",
    title = "Mortality Crossovers (8+ years education)",
    subtitle = "Pooled cohorts of 1890 - 1905"
  ) +
    scale_shape_manual(values = c(21, 24)) + 
  ggsci::scale_colour_lancet() +
  theme(legend.title = element_blank()) +
  theme(
    legend.position = c(.999, 0.001),
    legend.justification = c("right", "bottom"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6),
    legend.background = element_rect(color = "black", size = .5, linetype = "solid")
  )

## Calculate mortality rates — low education 
mortality_rates_loweduc <- dmf %>%
  filter(educ < 8) %>%
  filter(byear %in% c(1890:1905)) %>%
  filter(race == "White Americans" | race == "Black Americans") %>%
  group_by(death_age, race) %>%
  summarize(weighted_total = n()) %>%
  group_by(race) %>%
  mutate(lx = sum(weighted_total) - cumsum(weighted_total) + weighted_total) %>%
  mutate(mx = weighted_total / (lx + lead(lx) / 2)) %>%
  mutate(hazard = log(mx)) %>%
  mutate(hazard_avg = zoo::rollmean(x = hazard, k = 3, na.pad = T))

## Plot low education  
pooled_bwcrossover_loweduc <- mortality_rates_loweduc %>%
  filter(death_age %in% c(75:100)) %>%
  ggplot() +
  geom_line(aes(x = death_age, y = hazard, color = race)) +
  geom_point(aes(x = death_age, y = hazard, shape = race, color = race), size = 2.5, fill = "white") +
  theme_cowplot() + 
  geom_vline(xintercept = 86, linetype = "dashed") +
  theme(legend.position = "bottom") +
  labs(
    x = "Age",
    y = "Log(Mx)",
    title = "Mortality Crossovers (<8 years education)",
    subtitle = "Pooled cohorts of 1890 - 1905"
  ) +
    scale_shape_manual(values = c(21, 24)) + 
  ggsci::scale_colour_lancet() +
  theme(legend.title = element_blank()) +
  theme(
    legend.position = c(.999, 0.001),
    legend.justification = c("right", "bottom"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6),
    legend.background = element_rect(color = "black", size = .5, linetype = "solid")
  )

## crossover figures 
crossover_figure <- plot_grid(pooled_bwcrossover_loweduc, pooled_bwcrossover_highed, labels = "auto", ncol = 1)

## create plot 
ggsave(plot = crossover_figure, filename = here("figures/bw_crossover_education.png"), width = 7.5, height = 10)
```

## income 

```{r}
## estimate mortality rate
estimated_mortality_rates <- dmf %>%
  filter(incwage %in% 1:1000) %>%
  filter(byear %in% c(1890:1905)) %>%
  filter(race == "White Americans" | race == "Black Americans") %>%
  group_by(death_age, race) %>%
  summarize(weighted_total = n()) %>%
  group_by(race) %>%
  mutate(lx = sum(weighted_total) - cumsum(weighted_total) + weighted_total) %>%
  mutate(mx = weighted_total / (lx + lead(lx) / 2)) %>%
  mutate(hazard = log(mx)) # %>%
#  mutate(hazard_avg = zoo::rollmean(x = hazard, k = 3, na.pad = T))

pooled_bwcrossover_highinc <- estimated_mortality_rates %>%
  filter(death_age %in% c(75:100)) %>%
  ggplot() +
  geom_line(aes(x = death_age, y = hazard, color = race)) +
  geom_point(aes(x = death_age, y = hazard, shape = race, color = race), size = 2.5, fill = "white") +
  theme_cowplot() + 
  geom_vline(xintercept = 86, linetype = "dashed") +
  theme(legend.position = "bottom") +
  labs(
    x = "Age",
    y = "Log(Mx)",
    title = "Mortality Crossovers (high income)",
    subtitle = "Pooled cohorts of 1890 - 1905"
  ) +
    scale_shape_manual(values = c(21, 24)) + 
  ggsci::scale_colour_lancet() +
  theme(legend.title = element_blank()) +
  theme(
    legend.position = c(.999, 0.001),
    legend.justification = c("right", "bottom"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6),
    legend.background = element_rect(color = "black", size = .5, linetype = "solid")
  )

## estimate mortality rate
estimated_mortality_rates <- dmf %>%
  filter(incwage %in% 1001:5030) %>%
  filter(byear %in% c(1890:1905)) %>%
  filter(race == "White Americans" | race == "Black Americans") %>%
  group_by(death_age, race) %>%
  summarize(weighted_total = n()) %>%
  group_by(race) %>%
  mutate(lx = sum(weighted_total) - cumsum(weighted_total) + weighted_total) %>%
  mutate(mx = weighted_total / (lx + lead(lx) / 2)) %>%
  mutate(hazard = log(mx)) # %>%
#  mutate(hazard_avg = zoo::rollmean(x = hazard, k = 3, na.pad = T))

pooled_bwcrossover_lowinc <- estimated_mortality_rates %>%
  filter(death_age %in% c(75:100)) %>%
  ggplot() +
  geom_line(aes(x = death_age, y = hazard, color = race)) +
  geom_point(aes(x = death_age, y = hazard, shape = race, color = race), size = 2.5, fill = "white") +
  theme_cowplot() + 
  geom_vline(xintercept = 86, linetype = "dashed") +
  theme(legend.position = "bottom") +
  labs(
    x = "Age",
    y = "Log(Mx)",
    title = "Mortality Crossovers (low income)",
    subtitle = "Pooled cohorts of 1890 - 1905"
  ) +
    scale_shape_manual(values = c(21, 24)) + 
  ggsci::scale_colour_lancet() +
  theme(legend.title = element_blank()) +
  theme(
    legend.position = c(.999, 0.001),
    legend.justification = c("right", "bottom"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6),
    legend.background = element_rect(color = "black", size = .5, linetype = "solid")
  )

## crossover figures 
crossover_figure <- plot_grid(pooled_bwcrossover_highinc, pooled_bwcrossover_lowinc, labels = "auto", ncol = 1)

## create plot 
ggsave(plot = crossover_figure, filename = here("figures/bw_crossover_income.png"), width = 7.5, height = 10)
```

## Homeownership 

```{r}
## estimate mortality rate
mr_ownhome <- dmf %>%
  filter(ownershp == 1) %>%
  filter(byear %in% c(1890:1905)) %>%
  filter(race == "White Americans" | race == "Black Americans") %>%
  group_by(death_age, race) %>%
  summarize(weighted_total = n()) %>%
  group_by(race) %>%
  mutate(lx = sum(weighted_total) - cumsum(weighted_total) + weighted_total) %>%
  mutate(mx = weighted_total / (lx + lead(lx) / 2)) %>%
  mutate(hazard = log(mx)) # %>%
#  mutate(hazard_avg = zoo::rollmean(x = hazard, k = 3, na.pad = T))

pooled_bwcrossover_home_own <- mr_ownhome %>%
  filter(death_age %in% c(75:100)) %>%
  ggplot() +
  geom_line(aes(x = death_age, y = hazard, color = race)) +
  geom_point(aes(x = death_age, y = hazard, shape = race, color = race), size = 2.5, fill = "white") +
  theme_cowplot() + 
  geom_vline(xintercept = 86, linetype = "dashed") +
  theme(legend.position = "bottom") +
  labs(
    x = "Age",
    y = "Log(Mx)",
    title = "Mortality Crossovers (Homeowner)",
    subtitle = "Pooled cohorts of 1890 - 1905"
  ) +
    scale_shape_manual(values = c(21, 24)) + 
  ggsci::scale_colour_lancet() +
  theme(legend.title = element_blank()) +
  theme(
    legend.position = c(.999, 0.001),
    legend.justification = c("right", "bottom"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6),
    legend.background = element_rect(color = "black", size = .5, linetype = "solid")
  )

## estimate mortality rate
mr_rent <- dmf %>%
  filter(ownershp == 2) %>%
  filter(byear %in% c(1890:1905)) %>%
  filter(race == "White Americans" | race == "Black Americans") %>%
  group_by(death_age, race) %>%
  summarize(weighted_total = n()) %>%
  group_by(race) %>%
  mutate(lx = sum(weighted_total) - cumsum(weighted_total) + weighted_total) %>%
  mutate(mx = weighted_total / (lx + lead(lx) / 2)) %>%
  mutate(hazard = log(mx)) # %>%
#  mutate(hazard_avg = zoo::rollmean(x = hazard, k = 3, na.pad = T))

pooled_bwcrossover_home_rent <- mr_rent %>%
  filter(death_age %in% c(75:100)) %>%
  ggplot() +
  geom_line(aes(x = death_age, y = hazard, color = race)) +
  geom_point(aes(x = death_age, y = hazard, shape = race, color = race), size = 2.5, fill = "white") +
  theme_cowplot() + 
  geom_vline(xintercept = 86, linetype = "dashed") +
  theme(legend.position = "bottom") +
  labs(
    x = "Age",
    y = "Log(Mx)",
    title = "Mortality Crossovers (Renter)",
    subtitle = "Pooled cohorts of 1890 - 1905"
  ) +
    scale_shape_manual(values = c(21, 24)) + 
  ggsci::scale_colour_lancet() +
  theme(legend.title = element_blank()) +
  theme(
    legend.position = c(.999, 0.001),
    legend.justification = c("right", "bottom"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6),
    legend.background = element_rect(color = "black", size = .5, linetype = "solid")
  )

## crossover figures 
crossover_figure <- plot_grid(pooled_bwcrossover_home_own, pooled_bwcrossover_home_rent, labels = "auto", ncol = 1)

## create plot 
ggsave(plot = crossover_figure, filename = here("figures/bw_crossover_homeowner.png"), width = 7.5, height = 10)
```

## combine plot 

```{r}
bw_crossover_subgroups <- plot_grid(pooled_bwcrossover_loweduc, pooled_bwcrossover_highed, pooled_bwcrossover_highinc, pooled_bwcrossover_lowinc, pooled_bwcrossover_home_own, pooled_bwcrossover_home_rent, labels = "auto", ncol = 2)

ggsave(plot = bw_crossover_subgroups, filename = here("figures/bw_crossover_subgroups.png"), width = 10, height = 14)
```


## SES Crossovers 

```{r}
## estimate mortality rate
estimated_mortality_rates <- dmf %>%
  filter(educ_yrs %in% c(0:12, 12:20)) %>%
  mutate(hs = case_when(
    educ_yrs >= 12 ~ "High School",
    TRUE ~ "No High School"
  )) %>%
  filter(byear %in% c(1890:1905)) %>%
  filter(race == "White Americans") %>%
  group_by(death_age, hs) %>%
  summarize(weighted_total = n()) %>%
  group_by(hs) %>%
  mutate(lx = sum(weighted_total) - cumsum(weighted_total) + weighted_total) %>%
  mutate(mx = weighted_total / (lx + lead(lx) / 2)) %>%
  mutate(hazard = log(mx)) # %>%
#  mutate(hazard_avg = zoo::rollmean(x = hazard, k = 3, na.pad = T))

pooled_bwcrossover_education <- estimated_mortality_rates %>%
  filter(death_age %in% c(75:100)) %>%
  ggplot() +
  geom_point(aes(x = death_age, y = hazard, shape = hs, color = hs), size = 4) +
  geom_line(aes(x = death_age, y = hazard, color = hs)) +
  theme_bw(base_size = 25) +
  geom_vline(xintercept = 95, linetype = "dashed") +
  theme(legend.position = "bottom") +
  labs(
    x = "Age",
    y = "Log(Mx)",
    title = "Education - Mortality Crossovers (Men)",
    subtitle = "Pooled cohorts of 1890 - 1905"
  ) +
  ggsci::scale_colour_lancet() +
  theme(legend.title = element_blank()) +
  theme(
    legend.position = c(.999, 0.001),
    legend.justification = c("right", "bottom"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6),
    legend.background = element_rect(color = "black", size = .5, linetype = "solid")
  )

## estimate mortality rate
estimated_mortality_rates <- dmf %>%
  filter(incwage %in% 1:5030) %>%
  mutate(inc_binary = case_when(
    incwage >= 1000 ~ "High Income (>$1000)",
    TRUE ~ "Low Income (<$1000)"
  )) %>%
  filter(byear %in% c(1890:1905)) %>%
  group_by(death_age, inc_binary) %>%
  summarize(weighted_total = n()) %>%
  group_by(inc_binary) %>%
  mutate(lx = sum(weighted_total) - cumsum(weighted_total) + weighted_total) %>%
  mutate(mx = weighted_total / (lx + lead(lx) / 2)) %>%
  mutate(hazard = log(mx)) # %>%
#  mutate(hazard_avg = zoo::rollmean(x = hazard, k = 3, na.pad = T))

pooled_bwcrossover_income <- estimated_mortality_rates %>%
  filter(death_age %in% c(75:100)) %>%
  ggplot() +
  geom_point(aes(x = death_age, y = hazard, shape = inc_binary, color = inc_binary), size = 4) +
  geom_line(aes(x = death_age, y = hazard, color = inc_binary)) +
  theme_bw(base_size = 25) +
  geom_vline(xintercept = 95, linetype = "dashed") +
  theme(legend.position = "bottom") +
  labs(
    x = "Age",
    y = "Log(Mx)",
    title = "Wage income - Mortality Crossover (Men)",
    subtitle = "Pooled cohorts of 1890 - 1905"
  ) +
  ggsci::scale_colour_lancet() +
  theme(legend.title = element_blank()) +
  theme(
    legend.position = c(.999, 0.001),
    legend.justification = c("right", "bottom"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6),
    legend.background = element_rect(color = "black", size = .5, linetype = "solid")
  )

crossover_figure_ses <- plot_grid(pooled_bwcrossover_education, pooled_bwcrossover_income, labels = "auto", ncol = 1)

ggsave(plot = crossover_figure_ses, filename = here("figures/ses_crossover.png"), width = 15, height = 20)
```





